/**
 * Board (TSV) compiler — the storyboard `{slug}_storyboard.tsv` is a PROJECTION of the
 * per-shot `shot.md` files, not a hand-maintained artifact. This makes the at-a-glance board
 * provably consistent with the shots (kills A3 three-layer drift for the TSV layer) and removes
 * the manual upkeep that slows authoring.
 *
 *   - compileBoardTsv: regenerate the TSV from shot.md, preserving the project's column order
 *     and any board-only columns (e.g. "Shot image", a manual link) per shot.
 *   - boardDrift:      diff the on-disk TSV against the projection on the authoritative columns
 *     (the L05 cross-layer check).
 */
import fs from "fs";
import path from "path";
import type { ProjectIndex, Shot } from "../types.js";

const DEFAULT_HEADERS = [
  "Shot", "Place / Setting", "Emotion", "Shot Type", "Camera Movement", "Duration",
  "Color & Mood", "Subject & Action", "VO/Lines", "SFX / Audio", "Shot image", "Notes",
];

function norm(h: string): string {
  return h.toLowerCase().replace(/[\s/&]+/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
}

// Authoritative columns: their value comes FROM shot.md. Anything else (Shot image, …) is
// board-only and preserved verbatim from the existing TSV.
const COLUMN_SOURCE: Record<string, (s: Shot) => string> = {
  shot: (s) => s.code,
  place_setting: (s) => s.meta.setting ?? "",
  setting: (s) => s.meta.setting ?? "",
  emotion: (s) => s.meta.emotion ?? "",
  shot_type: (s) => s.meta.shot_type ?? "",
  camera_movement: (s) => s.meta.camera ?? "",
  camera: (s) => s.meta.camera ?? "",
  duration: (s) => s.meta.duration ?? "",
  color_mood: (s) => s.meta.color_mood ?? "",
  subject_action: (s) => s.content.subject_action ?? "",
  vo_lines: (s) => s.content.vo_lines ?? "",
  sfx_audio: (s) => s.content.sfx_audio ?? "",
  notes: (s) => s.content.notes ?? "",
};

export interface ParsedBoard {
  headers: string[];
  /** shotCode → row cells (aligned to headers). */
  rows: Map<string, string[]>;
  /** shot codes in their on-disk order. */
  order: string[];
}

export function parseBoardTsv(raw: string): ParsedBoard {
  const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
  if (lines.length === 0) return { headers: [...DEFAULT_HEADERS], rows: new Map(), order: [] };
  const headers = lines[0].split("\t").map((h) => h.trim());
  const rows = new Map<string, string[]>();
  const order: string[] = [];
  for (const line of lines.slice(1)) {
    const cells = line.split("\t");
    const code = (cells[0] ?? "").trim();
    if (!code) continue;
    rows.set(code, cells);
    order.push(code);
  }
  return { headers, rows, order };
}

/** TSV-escape: tabs/newlines would break the row, so collapse them to spaces. */
function cell(v: string): string {
  return (v ?? "").replace(/[\t\r\n]+/g, " ").trim();
}

/** The projected row for a shot, given the header set and any existing row to preserve board-only cells from. */
function projectRow(shot: Shot, headers: string[], existing?: string[]): string[] {
  return headers.map((h, i) => {
    const src = COLUMN_SOURCE[norm(h)];
    if (src) return cell(src(shot));
    return cell(existing?.[i] ?? ""); // board-only column (e.g. "Shot image") — preserve
  });
}

export function compileBoardTsv(project: ProjectIndex, existingRaw?: string): string {
  const existing = existingRaw ? parseBoardTsv(existingRaw) : null;
  const headers = existing?.headers.length ? existing.headers : [...DEFAULT_HEADERS];
  const byCode = new Map(project.shots.map((s) => [s.code, s]));

  // Preserve the board's existing row order; append any shots not yet on the board (in shot order).
  const ordered: Shot[] = [];
  const seen = new Set<string>();
  for (const code of existing?.order ?? []) {
    const s = byCode.get(code);
    if (s) { ordered.push(s); seen.add(code); }
  }
  for (const s of project.shots) if (!seen.has(s.code)) ordered.push(s);

  const lines = [headers.join("\t")];
  for (const s of ordered) lines.push(projectRow(s, headers, existing?.rows.get(s.code)).join("\t"));
  return lines.join("\n") + "\n";
}

export interface BoardDriftRow {
  shotCode: string;
  column: string;
  board: string;
  shotMd: string;
}

/**
 * Columns that are the SAME datum in the board and shot.md — a mismatch is a real bookkeeping
 * bug (wrong duration, wrong location). The prose columns (Subject & Action, Color & Mood, VO,
 * SFX, Notes) are legitimately summarized/reformatted on an at-a-glance board, so they are NOT
 * linted — only regenerated by `sync-board --write` when the author opts into a full projection.
 */
export const STRUCTURED_BOARD_COLUMNS = new Set(["shot", "place_setting", "setting", "duration"]);

export function isStructuredColumn(header: string): boolean {
  return STRUCTURED_BOARD_COLUMNS.has(norm(header));
}

/** L05: where the on-disk TSV disagrees with the shot.md projection, on authoritative columns only. */
export function boardDrift(project: ProjectIndex, existingRaw: string): BoardDriftRow[] {
  const board = parseBoardTsv(existingRaw);
  const byCode = new Map(project.shots.map((s) => [s.code, s]));
  const out: BoardDriftRow[] = [];
  for (const code of board.order) {
    const shot = byCode.get(code);
    if (!shot) continue; // a board row with no shot dir — orphan, not a drift we can resolve here
    const cells = board.rows.get(code)!;
    board.headers.forEach((h, i) => {
      const src = COLUMN_SOURCE[norm(h)];
      if (!src) return; // board-only column — not authoritative
      const expected = cell(src(shot));
      const actual = cell(cells[i] ?? "");
      if (expected !== actual) out.push({ shotCode: code, column: h, board: actual, shotMd: expected });
    });
  }
  return out;
}

/** Locate the board TSV in a project dir (`{slug}_storyboard.tsv`, or any `*_storyboard.tsv`). */
export function findBoardTsv(projectDir: string, slug?: string): string | null {
  if (slug) {
    const p = path.join(projectDir, `${slug}_storyboard.tsv`);
    if (fs.existsSync(p)) return p;
  }
  if (!fs.existsSync(projectDir)) return null;
  const hit = fs.readdirSync(projectDir).find((f) => f.endsWith("_storyboard.tsv"));
  return hit ? path.join(projectDir, hit) : null;
}
